main : Electro\Vouchers\Vouchers
name: Vouchers
version: 2.0.0
api: 5.0.0
Author: Electro

commands:
  voucher:
    description: Create a voucher
    usage: /voucher <create/info>
    permission: vouchers.cmd
    
permissions:
  vouchers.cmd:
    default: op
    description: Permission to use the Voucher command

